services:
  snipeit-app:
    image: snipeit-app:latest
    container_name: snipeit-app
    ports:
      - "8088:80"
    environment:
      APP_ENV: production
      APP_DEBUG: false
      APP_KEY: base64:sR9ymCr+5VWY0cwJjF55QAC2vmFjf/MuH0xXc5RtfWc=
      DB_HOST: mysql
      DB_DATABASE: snipeit
      DB_USERNAME: snipeit
      DB_PASSWORD: password
